name: r7rs-compability-report

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "17 4 * * 2"

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        scheme:
          - capyscheme
          - chibi
          - chicken
          - cyclone
          - foment
          - gauche
          - gambit
          - guile
          - loko
          - kawa
          - larceny
          - meevax
          - mit-scheme
          - mosh
          - racket
          - sagittarius
          - skint
          - stklos
          - tr7
          - ypsilon
    runs-on: ubuntu-24.04
    container:
      image: debian
    steps:
      - uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/results
          key: results
          restore-keys: results
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        run: apt-get update && apt-get install -y make docker.io
      - name: Tests
        run: make CURRENT_DIR=${{ github.workspace }} SCHEME=${{ matrix.scheme }} test-docker
      - name: Upload results
        uses: actions/upload-artifact@main
        with:
          name: results-${{ matrix.scheme }}
          path: ${{ github.workspace }}/results/${{ matrix.scheme }}.csv
  Report:
    runs-on: ubuntu-24.04
    needs: Tests
    container:
      image: schemers/gauche:head
    steps:
      - uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/results
          key: results
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        run: apt-get update && apt-get install -y make
      - name: Download results
        uses: actions/download-artifact@main
        with:
          path: ${{ github.workspace }}/results
          merge-multiple: true
      - name: Report
        run: make report
      - name: Upload report
        uses: actions/upload-artifact@main
        with:
          name: report
          path: ${{ github.workspace }}/index.html